export const dummyOrders = [
  {
    id: 186,
    orderNo: "220610122517",
    orderDate: "2022-06-10 12:25:17",
    orderLat: 0,
    orderLon: 0,
    orderAddress: "Achimota School, Accra Ghana",
    orderBy: "Assan",
    orderPhone: "0549546822",
    orderEmail: "assanenathaniel@gmail.com",
    orderDetail: [
      {
        id: 187,
        orderId: "186",
        orderNo: "220610122517",
        organization: "POTBELLY",
        done: false,
        menuItem: "Americano Feed 1",
        category: "BBQ",
        type: "Traditional BBQ Combo",
        tagName: "Americano",
        imageUrl:
          "https://cbsg-static-data-files.s3.us-east-2.amazonaws.com/potbelly/Screenshot 2022-06-08 at 12.37.02 PM-min.png\n",
        price: 135,
        quantity: 5,
        total: 675,
        size: "",
        description:
          "Portions of Pork Ribs, Side of Mash Potatoes, Potatoe Salad, Cole Slaw and Hot Dogs",
      },
    ],
    orderAdditionalInfo: "",
    orderStatus: "Pending",
    orderTotalAmount: 675,
    orderQuantity: 1,
    orderBranch: "Osu",
    channel: "walk-in",
    dispatcher: null,
    dispatcherPhone: null,
    distance: 0,
    eta: 0,
    deliveryDate: null,
    acknowledgementDate: null,
    paymentAmount: 0,
    paymentNo: null,
    orderTakenBy: null,
    chef: null,
    simpleType: "Americano Feed 1",
  },
  {
    id: 184,
    orderNo: "220610112941",
    orderDate: "2022-06-10 11:29:41",
    orderLat: 0,
    orderLon: 0,
    orderAddress: "GT-92344",
    orderBy: "Marilyn",
    orderPhone: "+233202656398",
    orderEmail: "hinnehwilliams@gmail.com",
    orderDetail: [
      {
        id: 185,
        orderNo: "220610112941",
        organization: "POTBELLY",
        done: true,
        menuItem: "Americano Feed 1",
        category: "BBQ",
        type: "Traditional BBQ Combo",
        tagName: "Americano",
        imageUrl:
          "https://cbsg-static-data-files.s3.us-east-2.amazonaws.com/potbelly/Screenshot 2022-06-08 at 12.37.02 PM-min.png\n",
        price: 135,
        quantity: 1,
        total: 135,
        size: "",
        description:
          "Portions of Pork Ribs, Side of Mash Potatoes, Potatoe Salad, Cole Slaw and Hot Dogs",
      },
      {
        id: 185,
        orderNo: "220610112941",
        organization: "POTBELLY",
        done: true,
        menuItem: "Americano Feed 1",
        category: "BBQ",
        type: "Traditional BBQ Combo",
        tagName: "Americano",
        imageUrl:
          "https://cbsg-static-data-files.s3.us-east-2.amazonaws.com/potbelly/Screenshot 2022-06-08 at 12.37.02 PM-min.png\n",
        price: 135,
        quantity: 1,
        total: 135,
        size: "",
        description:
          "Portions of Pork Ribs, Side of Mash Potatoes, Potatoe Salad, Cole Slaw and Hot Dogs",
      },
    ],
    orderAdditionalInfo: " Additional info here! I wanted more textkkkkkkkkh",
    orderStatus: "Pending",
    orderTotalAmount: 135,
    orderQuantity: 1,
    orderBranch: "Osu",
    channel: "walk-in",
    dispatcher: null,
    dispatcherPhone: null,
    distance: 0,
    eta: 0,
    deliveryDate: null,
    acknowledgementDate: null,
    paymentAmount: 0,
    paymentNo: null,
    orderTakenBy: null,
    chef: null,
    simpleType: "Americano Feed 1",
  },
];

const a = {
  id: 94,
  organization: "POTBELLY",
  menuItem: "Lone Ranger",
  category: "Pizza",
  type: "Main",
  tagName: "Lone Ranger",
  imageUrl:
    "https://cbsg-static-data-files.s3.us-east-2.amazonaws.com/potbelly/light-bg.jpeg",
  price: 30,
  size: "Small",
  createdBy: "Super User",
  createOn: "2022-06-22 10:10:23",
  lastUpdated: "2022-06-22 10:10:23",
  lastUpdatedBy: null,
  likes: 0,
  cumulativeRating: 0,
  ratingFrequency: 0,
  branch: "Amrahia",
  description: "Test lone ranger",
  minOptions: 2,
  maxOptions: 2,
  minSauces: 2,
  maxSauces: 2,
  minSides: 2,
  maxSides: 2,
  minProtein: 2,
  maxProtein: 2,
  minDrinks: 2,
  maxDrinks: 2,
  chefGroup: "",
  applicableCategory: "string",
  mainDish: true,
};
