import { getAsObjectFromLocalStorage } from "../../contants/libraries/easy";

export const randomImages = "https://source.unsplash.com/random";

export const roles = [
  "Manager",
  "Kitchen-manager",
  "Waiter",
  "Frontdesk",
  "Rider",
  "Chef",
  "Super",
];

export const branches = ["Amrahia", "Osu", "Adjiringanor"];
export const menus = [
  "Main",
  "Options",
  "Sides",
  "Sauces",
  "Proteins",
  "Drinks",
];
export const sizes = ["Small", "Medium", "Large", "Extra Large"];
export const actionStatus = ["Pending", "Processing", "Processed"];

export const User = () => {
  let userData = getAsObjectFromLocalStorage("userData");
  if (!!userData) {
    return userData;
  }
  return { name: "", role: "" };
};

export const fakeData = [
  {
    id: 93,
    organization: "POTBELLY",
    menuItem: "Butchers delight",
    category: "Dessert",
    type: "Taste Buzzer",
    tagName: "Butchers delight",
    imageUrl:
      "https://cbsg-static-data-files.s3.us-east-2.amazonaws.com/potbelly/tropical-palm-leaf-cartoon-vector-23684417.jpeg",
    price: 0.1,
    size: "Medium",
    createdBy: "Super User",
    createOn: "2022-06-17 18:38:06",
    lastUpdated: "2022-06-17 18:38:06",
    lastUpdatedBy: null,
    likes: 0,
    cumulativeRating: 0,
    ratingFrequency: 0,
    branch: "Adjiringanor",
    description: "Nice tasty desert after evening super",
    minOptions: 0,
    maxOptions: 0,
    minSauces: 0,
    maxSauces: 0,
    minSides: 0,
    maxSides: 0,
    minProtein: 0,
    maxProtein: 0,
    minDrinks: 0,
    maxDrinks: 0,
    chefGroup: null,
    applicableCategory: null,
    mainDish: false,
  },
  {
    id: 92,
    organization: "POTBELLY",
    menuItem: "Butchers delight",
    category: "Dessert",
    type: "Taste Buzzer",
    tagName: "Butchers delight",
    imageUrl:
      "https://cbsg-static-data-files.s3.us-east-2.amazonaws.com/potbelly/tropical-palm-leaf-cartoon-vector-23684417.jpeg",
    price: 0.1,
    size: "Medium",
    createdBy: "Super User",
    createOn: "2022-06-17 18:38:06",
    lastUpdated: "2022-06-17 18:38:06",
    lastUpdatedBy: null,
    likes: 0,
    cumulativeRating: 0,
    ratingFrequency: 0,
    branch: "Osu",
    description: "Nice tasty desert after evening super",
    minOptions: 0,
    maxOptions: 0,
    minSauces: 0,
    maxSauces: 0,
    minSides: 0,
    maxSides: 0,
    minProtein: 0,
    maxProtein: 0,
    minDrinks: 0,
    maxDrinks: 0,
    chefGroup: null,
    applicableCategory: null,
    mainDish: false,
  },
  {
    id: 89,
    organization: "POTBELLY",
    menuItem: "Butchers delight",
    category: "Dessert",
    type: "Taste Buzzer",
    tagName: "Butchers delight",
    imageUrl:
      "https://cbsg-static-data-files.s3.us-east-2.amazonaws.com/potbelly/tropical-palm-leaf-cartoon-vector-23684417.jpeg",
    price: 0.1,
    size: "Medium",
    createdBy: "Super User",
    createOn: "2022-06-17 18:36:57",
    lastUpdated: "2022-06-17 18:36:57",
    lastUpdatedBy: null,
    likes: 0,
    cumulativeRating: 0,
    ratingFrequency: 0,
    branch: "Osu",
    description: "Nice tasty desert after evening super",
    minOptions: 0,
    maxOptions: 0,
    minSauces: 0,
    maxSauces: 0,
    minSides: 0,
    maxSides: 0,
    minProtein: 0,
    maxProtein: 0,
    minDrinks: 0,
    maxDrinks: 0,
    chefGroup: null,
    applicableCategory: null,
    mainDish: false,
  },
  {
    id: 90,
    organization: "POTBELLY",
    menuItem: "Butchers delight",
    category: "Dessert",
    type: "Taste Buzzer",
    tagName: "Butchers delight",
    imageUrl:
      "https://cbsg-static-data-files.s3.us-east-2.amazonaws.com/potbelly/tropical-palm-leaf-cartoon-vector-23684417.jpeg",
    price: 0.1,
    size: "Medium",
    createdBy: "Super User",
    createOn: "2022-06-17 18:36:57",
    lastUpdated: "2022-06-17 18:36:57",
    lastUpdatedBy: null,
    likes: 0,
    cumulativeRating: 0,
    ratingFrequency: 0,
    branch: "Adjiringanor",
    description: "Nice tasty desert after evening super",
    minOptions: 0,
    maxOptions: 0,
    minSauces: 0,
    maxSauces: 0,
    minSides: 0,
    maxSides: 0,
    minProtein: 0,
    maxProtein: 0,
    minDrinks: 0,
    maxDrinks: 0,
    chefGroup: null,
    applicableCategory: null,
    mainDish: false,
  },
  {
    id: 91,
    organization: "POTBELLY",
    menuItem: "Butchers delight",
    category: "Dessert",
    type: "Taste Buzzer",
    tagName: "Butchers delight",
    imageUrl:
      "https://cbsg-static-data-files.s3.us-east-2.amazonaws.com/potbelly/tropical-palm-leaf-cartoon-vector-23684417.jpeg",
    price: 0.1,
    size: "Medium",
    createdBy: "Super User",
    createOn: "2022-06-17 18:38:06",
    lastUpdated: "2022-06-17 18:38:06",
    lastUpdatedBy: null,
    likes: 0,
    cumulativeRating: 0,
    ratingFrequency: 0,
    branch: "Amrahia",
    description: "Nice tasty desert after evening super",
    minOptions: 0,
    maxOptions: 0,
    minSauces: 0,
    maxSauces: 0,
    minSides: 0,
    maxSides: 0,
    minProtein: 0,
    maxProtein: 0,
    minDrinks: 0,
    maxDrinks: 0,
    chefGroup: null,
    applicableCategory: null,
    mainDish: false,
  },
  {
    id: 88,
    organization: "POTBELLY",
    menuItem: "Butchers delight",
    category: "Dessert",
    type: "Taste Buzzer",
    tagName: "Butchers delight",
    imageUrl:
      "https://cbsg-static-data-files.s3.us-east-2.amazonaws.com/potbelly/tropical-palm-leaf-cartoon-vector-23684417.jpeg",
    price: 0.1,
    size: "Medium",
    createdBy: "Super User",
    createOn: "2022-06-17 18:36:57",
    lastUpdated: "2022-06-17 18:36:57",
    lastUpdatedBy: null,
    likes: 0,
    cumulativeRating: 0,
    ratingFrequency: 0,
    branch: "Amrahia",
    description: "Nice tasty desert after evening super",
    minOptions: 0,
    maxOptions: 0,
    minSauces: 0,
    maxSauces: 0,
    minSides: 0,
    maxSides: 0,
    minProtein: 0,
    maxProtein: 0,
    minDrinks: 0,
    maxDrinks: 0,
    chefGroup: null,
    applicableCategory: null,
    mainDish: false,
  },
  {
    id: 87,
    organization: "POTBELLY",
    menuItem: "Gob3 Star",
    category: "Promo",
    type: "burgergar",
    tagName: "Jumbo1",
    imageUrl:
      "https://cbsg-static-data-files.s3.us-east-2.amazonaws.com/potbelly/117b03b2-c6b3-46e4-9332-75755283c5ab.jpeg",
    price: 0.1,
    size: "Medium",
    createdBy: "Super User",
    createOn: "2022-06-17 18:02:45",
    lastUpdated: "2022-06-17 18:02:45",
    lastUpdatedBy: null,
    likes: 0,
    cumulativeRating: 0,
    ratingFrequency: 0,
    branch: "Amrahia",
    description: "No description",
    minOptions: 0,
    maxOptions: 0,
    minSauces: 0,
    maxSauces: 0,
    minSides: 0,
    maxSides: 0,
    minProtein: 0,
    maxProtein: 0,
    minDrinks: 0,
    maxDrinks: 0,
    chefGroup: null,
    applicableCategory: null,
    mainDish: false,
  },
  {
    id: 86,
    organization: "POTBELLY",
    menuItem: "Gob3 Star",
    category: "Promo",
    type: "burgergar",
    tagName: "Jumbo1",
    imageUrl:
      "https://cbsg-static-data-files.s3.us-east-2.amazonaws.com/potbelly/117b03b2-c6b3-46e4-9332-75755283c5ab.jpeg",
    price: 0.1,
    size: "Medium",
    createdBy: "Super User",
    createOn: "2022-06-17 18:02:45",
    lastUpdated: "2022-06-17 18:02:45",
    lastUpdatedBy: null,
    likes: 0,
    cumulativeRating: 0,
    ratingFrequency: 0,
    branch: "Osu",
    description: "No description",
    minOptions: 0,
    maxOptions: 0,
    minSauces: 0,
    maxSauces: 0,
    minSides: 0,
    maxSides: 0,
    minProtein: 0,
    maxProtein: 0,
    minDrinks: 0,
    maxDrinks: 0,
    chefGroup: null,
    applicableCategory: null,
    mainDish: false,
  },
  {
    id: 85,
    organization: "POTBELLY",
    menuItem: "Pretty Beans",
    category: "Other",
    type: "Beans",
    tagName: "Akwesi Gob3One",
    imageUrl:
      "https://cbsg-static-data-files.s3.us-east-2.amazonaws.com/potbelly/117b03b2-c6b3-46e4-9332-75755283c5ab.jpeg",
    price: 30,
    size: "Medium",
    createdBy: "Sys Admin",
    createOn: "2022-06-17 15:30:53",
    lastUpdated: "2022-06-17 15:34:34",
    lastUpdatedBy: "Sys Admin",
    likes: 0,
    cumulativeRating: 0,
    ratingFrequency: 0,
    branch: "Adjiringanor",
    description: "Description",
    minOptions: 0,
    maxOptions: 0,
    minSauces: 0,
    maxSauces: 0,
    minSides: 0,
    maxSides: 0,
    minProtein: 0,
    maxProtein: 0,
    minDrinks: 0,
    maxDrinks: 0,
    chefGroup: null,
    applicableCategory: null,
    mainDish: false,
  },
  {
    id: 84,
    organization: "POTBELLY",
    menuItem: "Pretty Beans",
    category: "Sandwich",
    type: "Beans",
    tagName: "Akwesi Gob3One",
    imageUrl:
      "https://cbsg-static-data-files.s3.us-east-2.amazonaws.com/potbelly/117b03b2-c6b3-46e4-9332-75755283c5ab.jpeg",
    price: 30,
    size: "Medium",
    createdBy: "Sys Admin",
    createOn: "2022-06-17 15:30:53",
    lastUpdated: "2022-06-17 15:30:53",
    lastUpdatedBy: null,
    likes: 0,
    cumulativeRating: 0,
    ratingFrequency: 0,
    branch: "Osu",
    description: "Description",
    minOptions: 0,
    maxOptions: 0,
    minSauces: 0,
    maxSauces: 0,
    minSides: 0,
    maxSides: 0,
    minProtein: 0,
    maxProtein: 0,
    minDrinks: 0,
    maxDrinks: 0,
    chefGroup: null,
    applicableCategory: null,
    mainDish: false,
  },
  {
    id: 81,
    organization: "POTBELLY",
    menuItem: "Waakye and Stew",
    category: "Promo",
    type: "Whatsapp",
    tagName: "Akwesi Gob3One",
    imageUrl:
      "https://cbsg-static-data-files.s3.us-east-2.amazonaws.com/potbelly/1_xl92hHDqKnBalWjAOYXprg.jpeg",
    price: 500,
    size: "Small",
    createdBy: "Sys Admin",
    createOn: "2022-06-17 11:57:00",
    lastUpdated: "2022-06-17 11:57:00",
    lastUpdatedBy: null,
    likes: 0,
    cumulativeRating: 0,
    ratingFrequency: 0,
    branch: "Osu",
    description: "Description",
    minOptions: 0,
    maxOptions: 0,
    minSauces: 0,
    maxSauces: 0,
    minSides: 0,
    maxSides: 0,
    minProtein: 0,
    maxProtein: 0,
    minDrinks: 0,
    maxDrinks: 0,
    chefGroup: null,
    applicableCategory: null,
    mainDish: false,
  },
  {
    id: 83,
    organization: "POTBELLY",
    menuItem: "Pretty Beans",
    category: "Sandwich",
    type: "Beans",
    tagName: "Akwesi Gob3One",
    imageUrl:
      "https://cbsg-static-data-files.s3.us-east-2.amazonaws.com/potbelly/117b03b2-c6b3-46e4-9332-75755283c5ab.jpeg",
    price: 30,
    size: "Medium",
    createdBy: "Sys Admin",
    createOn: "2022-06-17 15:30:53",
    lastUpdated: "2022-06-17 15:30:53",
    lastUpdatedBy: null,
    likes: 0,
    cumulativeRating: 0,
    ratingFrequency: 0,
    branch: "Amrahia",
    description: "Description",
    minOptions: 0,
    maxOptions: 0,
    minSauces: 0,
    maxSauces: 0,
    minSides: 0,
    maxSides: 0,
    minProtein: 0,
    maxProtein: 0,
    minDrinks: 0,
    maxDrinks: 0,
    chefGroup: null,
    applicableCategory: null,
    mainDish: false,
  },
  {
    id: 82,
    organization: "POTBELLY",
    menuItem: "Waakye and Stew",
    category: "Promo",
    type: "Whatsapp",
    tagName: "Waakye Number One",
    imageUrl:
      "https://cbsg-static-data-files.s3.us-east-2.amazonaws.com/potbelly/1_xl92hHDqKnBalWjAOYXprg.jpeg",
    price: 500,
    size: "Small",
    createdBy: "Sys Admin",
    createOn: "2022-06-17 11:57:00",
    lastUpdated: "2022-06-17 11:58:49",
    lastUpdatedBy: "Sys Admin",
    likes: 0,
    cumulativeRating: 0,
    ratingFrequency: 0,
    branch: "Adjiringanor",
    description: "Description",
    minOptions: 0,
    maxOptions: 0,
    minSauces: 0,
    maxSauces: 0,
    minSides: 0,
    maxSides: 0,
    minProtein: 0,
    maxProtein: 0,
    minDrinks: 0,
    maxDrinks: 0,
    chefGroup: null,
    applicableCategory: null,
    mainDish: false,
  },
  {
    id: 80,
    organization: "POTBELLY",
    menuItem: "Waakye and Stew",
    category: "Promo",
    type: "Whatsapp",
    tagName: "Akwesi Gob3One",
    imageUrl:
      "https://cbsg-static-data-files.s3.us-east-2.amazonaws.com/potbelly/1_xl92hHDqKnBalWjAOYXprg.jpeg",
    price: 500,
    size: "Small",
    createdBy: "Sys Admin",
    createOn: "2022-06-17 11:57:00",
    lastUpdated: "2022-06-17 11:57:00",
    lastUpdatedBy: null,
    likes: 0,
    cumulativeRating: 0,
    ratingFrequency: 0,
    branch: "Amrahia",
    description: "Description",
    minOptions: 0,
    maxOptions: 0,
    minSauces: 0,
    maxSauces: 0,
    minSides: 0,
    maxSides: 0,
    minProtein: 0,
    maxProtein: 0,
    minDrinks: 0,
    maxDrinks: 0,
    chefGroup: null,
    applicableCategory: null,
    mainDish: false,
  },
  {
    id: 73,
    organization: "POTBELLY",
    menuItem: "Sunrise Delight",
    category: "Pizza",
    type: "Tasty Sandwich",
    tagName: "Menu Items",
    imageUrl:
      "https://cbsg-static-data-files.s3.us-east-2.amazonaws.com/potbelly/kfc.jpeg",
    price: 0.1,
    size: "S",
    createdBy: "Nathaniel Ewudzi Assan",
    createOn: "2022-06-15 11:10:29",
    lastUpdated: "2022-06-16 12:39:32",
    lastUpdatedBy: "Manager one",
    likes: 0,
    cumulativeRating: 0,
    ratingFrequency: 0,
    branch: "Osu",
    description: "Description",
    minOptions: 0,
    maxOptions: 0,
    minSauces: 0,
    maxSauces: 0,
    minSides: 0,
    maxSides: 0,
    minProtein: 0,
    maxProtein: 0,
    minDrinks: 0,
    maxDrinks: 0,
    chefGroup: null,
    applicableCategory: null,
    mainDish: false,
  },
  {
    id: 72,
    organization: "POTBELLY",
    menuItem: "Butchers delight",
    category: "Pizza",
    type: "Super Deluxe",
    tagName: "Menu Items",
    imageUrl:
      "https://cbsg-static-data-files.s3.us-east-2.amazonaws.com/potbelly/kfc.jpeg",
    price: 0.12,
    size: "S",
    createdBy: "Nathaniel Ewudzi Assan",
    createOn: "2022-06-15 11:10:29",
    lastUpdated: "2022-06-16 12:43:15",
    lastUpdatedBy: "Manager one",
    likes: 0,
    cumulativeRating: 0,
    ratingFrequency: 0,
    branch: "Amrahia",
    description: "Description",
    minOptions: 0,
    maxOptions: 0,
    minSauces: 0,
    maxSauces: 0,
    minSides: 0,
    maxSides: 0,
    minProtein: 0,
    maxProtein: 0,
    minDrinks: 0,
    maxDrinks: 0,
    chefGroup: null,
    applicableCategory: null,
    mainDish: false,
  },
  {
    id: 71,
    organization: "POTBELLY",
    menuItem: "Butchers delight",
    category: "Pizza",
    type: "Fulani Delight",
    tagName: "Menu Items",
    imageUrl:
      "https://cbsg-static-data-files.s3.us-east-2.amazonaws.com/potbelly/kfc rice.jpeg",
    price: 0.1,
    size: "S",
    createdBy: "Nathaniel Ewudzi Assan",
    createOn: "2022-06-15 11:09:41",
    lastUpdated: "2022-06-16 12:42:45",
    lastUpdatedBy: "Manager one",
    likes: 0,
    cumulativeRating: 0,
    ratingFrequency: 0,
    branch: "Adjiringanor",
    description: "Description",
    minOptions: 0,
    maxOptions: 0,
    minSauces: 0,
    maxSauces: 0,
    minSides: 0,
    maxSides: 0,
    minProtein: 0,
    maxProtein: 0,
    minDrinks: 0,
    maxDrinks: 0,
    chefGroup: null,
    applicableCategory: null,
    mainDish: false,
  },
  {
    id: 69,
    organization: "POTBELLY",
    menuItem: "Butchers delight",
    category: "Pizza",
    type: "Classic Delight",
    tagName: "Menu Items",
    imageUrl:
      "https://cbsg-static-data-files.s3.us-east-2.amazonaws.com/potbelly/kfc rice.jpeg",
    price: 0.1,
    size: "S",
    createdBy: "Nathaniel Ewudzi Assan",
    createOn: "2022-06-15 11:09:41",
    lastUpdated: "2022-06-16 12:37:56",
    lastUpdatedBy: "Manager one",
    likes: 0,
    cumulativeRating: 0,
    ratingFrequency: 0,
    branch: "Amrahia",
    description: "Description",
    minOptions: 0,
    maxOptions: 0,
    minSauces: 0,
    maxSauces: 0,
    minSides: 0,
    maxSides: 0,
    minProtein: 0,
    maxProtein: 0,
    minDrinks: 0,
    maxDrinks: 0,
    chefGroup: null,
    applicableCategory: null,
    mainDish: false,
  },
  {
    id: 70,
    organization: "POTBELLY",
    menuItem: "Butchers delight",
    category: "Pizza",
    type: "Classic Delight",
    tagName: "Menu Items",
    imageUrl:
      "https://cbsg-static-data-files.s3.us-east-2.amazonaws.com/potbelly/kfc rice.jpeg",
    price: 0.2,
    size: "M",
    createdBy: "Nathaniel Ewudzi Assan",
    createOn: "2022-06-15 11:09:41",
    lastUpdated: "2022-06-16 12:36:36",
    lastUpdatedBy: "Manager one",
    likes: 0,
    cumulativeRating: 0,
    ratingFrequency: 0,
    branch: "Osu",
    description: "Description",
    minOptions: 0,
    maxOptions: 0,
    minSauces: 0,
    maxSauces: 0,
    minSides: 0,
    maxSides: 0,
    minProtein: 0,
    maxProtein: 0,
    minDrinks: 0,
    maxDrinks: 0,
    chefGroup: null,
    applicableCategory: null,
    mainDish: false,
  },
];
